version: '3'
services:
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-db-data:/data
  api_endpoint:
    build: ./app/
    depends_on:
      - "redis"
  https_reverse_proxy:
    container_name: reverse_proxy
    hostname: reverse-proxy
    image: nginx:stable-alpine
    ports:
      - 443:443
    volumes:
      - ./reverse_proxy/config:/etc/nginx
      - ./reverse_proxy/certs:/etc/ssl/private
volumes:
    redis-db-data:
